### PR TITLE
Implemented Fastify server for performance enhancements.

### PR DESCRIPTION
**Pull request by 7Silva**
Hello Vanilla-OS team,

In this pull request, **I implemented Fastify and removed Express**. I made this change because Fastify is much more **optimized for requests** than Express. Below, I will leave some benchmark screenshots, but you can also see others and do your own tests. The main changes include:

- **Removal of Express:** Express was removed as the web server.
- **Addition of Fastify as the web server:** Fastify was added as a faster and more efficient web server compared to Express.

**I did not change any logic behind the system**, I just made this replacement and **added some very useful options to Fastify**, such as:

- **RateLimit:** Limits the number of requests per minute. (Maximum of 100 requests per minute)
- **Cors:** Allows requests from different origins.
- **Helmet:** Adds important security headers to the server.

I created an `index` file that already creates the Chronos file and th
en starts the server. I thought about doing a check in the `index` to see if there is an existing Chronos configuration and, if there is, not to generate it again. However, I don't know if this would be useful for you, so I decided not to do it.

Overall, these are the changes that were made. **I hope they are useful and I look forward to your feedback**.

**Express Server:**
Express

**Fastify Server:**
Fastify

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Somehow this issue escaped from my radar. I'll take a look at it asap.

**Comment by mirkobrombin** [comment]
Looks good to me, need to be updated, I can take care of it.

**Comment by kbdharun** [comment]
> Looks good to me, need to be updated, I can take care of it.

Fixed the failing build (the package files weren't in sync, updated it with `npm install` and tested the changes locally). Rebase and merge seem to be blocked (can we use Squash & merge here @mirkobrombin? Or is there any other changes that you want to implement?)

**Comment by mirkobrombin** [comment]
Squash and merge is fine

**Pull request merged**
